Phm 483/create device resource
onemedical/FHIR-Converter pull request #29
Opened 2022-10-05 18:34 UTC by malabbasi01

https://jira.onemedical.com/browse/PHM-483

Implantable device tests, ensure all metadata fields are present according to http://hl7.org/fhir/us/core/STU5/StructureDefinition-us-core-implantable-device.html

2022-10-06 13:35 UTC, alyssa-gardiner requested changes
This looks awesome! A console log snuck in there but other than that looks great!!

2022-10-06 13:38 UTC, AnithaPal submitted a review, later dismissed
🔥  🎉  Looks good ship it

2022-10-06 17:06 UTC, malabbasi01 commented on src/lib/handlebars-converter/handlebars-helpers.js
> +                // console.log(ret)
removed

2022-10-06 17:06 UTC, malabbasi01 commented on src/templates/cda/Resources/Device2.hbs
> +<!--                codeable concept from participant.participant.playingDevice.code-->
removed

2022-10-06 20:02 UTC, alyssa-gardiner approved these changes

2022-10-10 17:57 UTC, alyssa-gardiner approved these changes

2022-10-10 17:58 UTC, merged